# Generated by Django 5.0.6 on 2024-07-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_images/default_image.jpg', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
