# Generated by Django 5.0.6 on 2024-08-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_address', models.CharField(max_length=255)),
                ('order_details', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
