# Generated by Django 5.0.6 on 2024-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
