# Generated by Django 5.0.6 on 2024-08-13 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('producer_category', models.IntegerField(choices=[(1, 'Welding'), (2, 'Metalworking'), (3, 'Sewing')], default=1)),
                ('budget_range', models.IntegerField(choices=[(1, 'Under $1,000'), (2, '$1,000 - $5,000')])),
                ('quantity', models.PositiveIntegerField()),
                ('payment_method', models.IntegerField(choices=[(1, 'Prepayment'), (2, 'Partial Prepayment'), (3, 'Payment upon Completion')])),
                ('material_source', models.IntegerField(choices=[(1, 'Supplier Provided'), (2, 'Client Provided'), (3, 'Other')])),
                ('delivery_option', models.IntegerField(choices=[(1, 'Standard Delivery'), (2, 'Express Delivery'), (3, 'Pickup')])),
                ('delivery_deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('agree_to_penalties', models.BooleanField(default=False)),
                ('agree_to_bonuses', models.BooleanField(default=False)),
                ('agree_to_arbitrator', models.BooleanField(default=False)),
                ('additional_information', models.TextField(blank=True)),
                ('file_attachments', models.FileField(blank=True, null=True, upload_to='order_files/')),
                ('file_count', models.PositiveIntegerField(default=1)),
                ('shipping_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
