# Generated by Django 5.0.6 on 2024-08-20 16:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderrequest_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='file_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='budget_range',
            field=models.IntegerField(choices=[(1, 'Under $1,000'), (2, '$1,000 - $5,000')], default=1),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='delivery_option',
            field=models.IntegerField(choices=[(1, 'Standard Delivery'), (2, 'Express Delivery'), (3, 'Pickup')], default=1),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='material_source',
            field=models.IntegerField(choices=[(1, 'Supplier Provided'), (2, 'Client Provided'), (3, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Prepayment'), (2, 'Partial Prepayment'), (3, 'Payment upon Completion')], default=1),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
